---
- name: This sets up ngnix webserver
  hosts: 18.205.114.72
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
